const express = require("express");
const { AdminController } = require("../controllers/admin.controller");
const {
  PlatformController,
} = require("../../platform/controllers/platform.controller");
const { authenticate } = require("../../../shared/middleware/authenticate");
const { allowRoles, allowPermissions } = require("../../../shared/middleware/access");
const { catchErrors } = require("../../../shared/middleware/catch-errors");
const {
  checkInput,
} = require("../../../shared/middleware/check-input");
const {
  referralAdminRoutes,
} = require("../../referral/routes/referral-admin.routes");
const {
  commonManagementRoutes,
} = require("./common-management.routes");
const { ROLES } = require("../../../shared/constants/roles");
const {
  adminOverviewSchema,
  listVendorsSchema,
  listUsersSchema,
  createManagedUserSchema,
  userParamSchema,
  updateUserSchema,
  deactivateUserSchema,
  updateVendorStatusSchema,
  moderationQueueSchema,
  moderateProductSchema,
  listOrdersSchema,
  listPaymentsSchema,
  createPayoutSchema,
  listPayoutsSchema,
  taxReportSchema,
  createInvoiceSchema,
  createApiKeySchema,
  listApiKeysSchema,
  createWebhookSubscriptionSchema,
  listWebhookSubscriptionsSchema,
  upsertFeatureFlagSchema,
  listFeatureFlagsSchema,
  realtimeAnalyticsSchema,
  returnsAnalyticsSchema,
  listChargebacksSchema,
  listDeadLetterSchema,
  deadLetterActionSchema,
  queueStatusSchema,
  queueActionSchema,
  createSubscriptionPlanSchema,
  listSubscriptionPlanSchema,
  subscriptionPlanParamSchema,
  updateSubscriptionPlanSchema,
  listPlatformSubscriptionsSchema,
  updatePlatformSubscriptionStatusSchema,
  createPlatformFeeConfigSchema,
  listPlatformFeeConfigSchema,
  platformFeeConfigParamSchema,
  updatePlatformFeeConfigSchema,
  listAccessModulesSchema,
  createAdminSchema,
  listAdminsSchema,
  createPlatformSubAdminSchema,
  listPlatformSubAdminsSchema,
  updatePlatformSubAdminModulesSchema,
} = require("../validation/admin.validation");
const {
  createCategorySchema,
  updateCategorySchema,
  listCategoriesSchema,
  categoryKeySchema,
  createProductFamilySchema,
  updateProductFamilySchema,
  listProductFamiliesSchema,
  productFamilyCodeSchema,
  createProductVariantSchema,
  updateProductVariantSchema,
  listProductVariantsSchema,
  productVariantIdSchema,
  createHsnCodeSchema,
  updateHsnCodeSchema,
  listHsnCodesSchema,
  hsnCodeSchema,
  createGeographySchema,
  updateGeographySchema,
  listGeographiesSchema,
  geographyCodeSchema,
  createContentPageSchema,
  updateContentPageSchema,
  listContentPagesSchema,
  contentPageSlugSchema,
} = require("../../platform/validation/platform.validation");

const adminRoutes = express.Router();
const adminController = new AdminController();
const platformController = new PlatformController();

adminRoutes.use(authenticate, allowRoles(ROLES.ADMIN, ROLES.SUB_ADMIN));
adminRoutes.use("/referral", referralAdminRoutes);
adminRoutes.use("/common", commonManagementRoutes);

adminRoutes.get(
  "/access/modules",
  checkInput(listAccessModulesSchema),
  catchErrors(adminController.listAccessModules),
);
adminRoutes.post(
  "/access/admins",
  allowRoles(ROLES.SUPER_ADMIN),
  checkInput(createAdminSchema),
  catchErrors(adminController.createAdmin),
);
adminRoutes.get(
  "/access/admins",
  allowRoles(ROLES.SUPER_ADMIN),
  checkInput(listAdminsSchema),
  catchErrors(adminController.listAdmins),
);
adminRoutes.post(
  "/access/sub-admins",
  allowRoles(ROLES.ADMIN, ROLES.SUB_ADMIN),
  allowPermissions("rbac:add"),
  checkInput(createPlatformSubAdminSchema),
  catchErrors(adminController.createPlatformSubAdmin),
);
adminRoutes.get(
  "/access/sub-admins",
  allowRoles(ROLES.ADMIN, ROLES.SUB_ADMIN),
  allowPermissions("rbac:view"),
  checkInput(listPlatformSubAdminsSchema),
  catchErrors(adminController.listPlatformSubAdmins),
);
adminRoutes.patch(
  "/access/sub-admins/:userId/modules",
  allowRoles(ROLES.ADMIN, ROLES.SUB_ADMIN),
  allowPermissions("rbac:update"),
  checkInput(updatePlatformSubAdminModulesSchema),
  catchErrors(adminController.updatePlatformSubAdminModules),
);

adminRoutes.get(
  "/dashboard/overview",
  checkInput(adminOverviewSchema),
  catchErrors(adminController.overview),
);
adminRoutes.get(
  "/users",
  checkInput(listUsersSchema),
  catchErrors(adminController.listUsers),
);
adminRoutes.post(
  "/users",
  checkInput(createManagedUserSchema),
  catchErrors(adminController.createUser),
);
adminRoutes.get(
  "/users/:userId",
  checkInput(userParamSchema),
  catchErrors(adminController.getUser),
);
adminRoutes.patch(
  "/users/:userId",
  checkInput(updateUserSchema),
  catchErrors(adminController.updateUser),
);
adminRoutes.delete(
  "/users/:userId",
  checkInput(deactivateUserSchema),
  catchErrors(adminController.deactivateUser),
);
adminRoutes.get(
  "/vendors",
  checkInput(listVendorsSchema),
  catchErrors(adminController.listVendors),
);
adminRoutes.patch(
  "/vendors/:sellerId/status",
  checkInput(updateVendorStatusSchema),
  catchErrors(adminController.updateVendorStatus),
);
adminRoutes.get(
  "/products/moderation-queue",
  checkInput(moderationQueueSchema),
  catchErrors(adminController.moderationQueue),
);
adminRoutes.patch(
  "/products/:productId/moderate",
  checkInput(moderateProductSchema),
  catchErrors(adminController.moderateProduct),
);
adminRoutes.get(
  "/orders",
  checkInput(listOrdersSchema),
  catchErrors(adminController.listOrders),
);
adminRoutes.get(
  "/payments",
  checkInput(listPaymentsSchema),
  catchErrors(adminController.listPayments),
);
adminRoutes.post(
  "/payouts",
  checkInput(createPayoutSchema),
  catchErrors(adminController.createPayout),
);
adminRoutes.get(
  "/payouts",
  checkInput(listPayoutsSchema),
  catchErrors(adminController.listPayouts),
);
adminRoutes.get(
  "/tax/reports",
  checkInput(taxReportSchema),
  catchErrors(adminController.taxReport),
);
adminRoutes.post(
  "/tax/orders/:orderId/invoice",
  checkInput(createInvoiceSchema),
  catchErrors(adminController.createInvoice),
);
adminRoutes.post(
  "/platform/api-keys",
  checkInput(createApiKeySchema),
  catchErrors(adminController.createApiKey),
);
adminRoutes.get(
  "/platform/api-keys",
  checkInput(listApiKeysSchema),
  catchErrors(adminController.listApiKeys),
);
adminRoutes.post(
  "/platform/webhooks",
  checkInput(createWebhookSubscriptionSchema),
  catchErrors(adminController.createWebhookSubscription),
);
adminRoutes.get(
  "/platform/webhooks",
  checkInput(listWebhookSubscriptionsSchema),
  catchErrors(adminController.listWebhookSubscriptions),
);
adminRoutes.put(
  "/platform/feature-flags",
  checkInput(upsertFeatureFlagSchema),
  catchErrors(adminController.upsertFeatureFlag),
);
adminRoutes.get(
  "/platform/feature-flags",
  checkInput(listFeatureFlagsSchema),
  catchErrors(adminController.listFeatureFlags),
);
adminRoutes.get(
  "/analytics/realtime",
  checkInput(realtimeAnalyticsSchema),
  catchErrors(adminController.realtimeAnalytics),
);
adminRoutes.get(
  "/returns/analytics",
  checkInput(returnsAnalyticsSchema),
  catchErrors(adminController.returnsAnalytics),
);
adminRoutes.get(
  "/chargebacks",
  checkInput(listChargebacksSchema),
  catchErrors(adminController.listChargebacks),
);
adminRoutes.get(
  "/system/health",
  checkInput(queueStatusSchema),
  catchErrors(adminController.systemHealth),
);
adminRoutes.get(
  "/system/queues",
  checkInput(queueStatusSchema),
  catchErrors(adminController.queueStatus),
);
adminRoutes.post(
  "/system/queues/:queueName/pause",
  checkInput(queueActionSchema),
  catchErrors(adminController.pauseQueue),
);
adminRoutes.post(
  "/system/queues/:queueName/resume",
  checkInput(queueActionSchema),
  catchErrors(adminController.resumeQueue),
);
adminRoutes.get(
  "/system/dead-letter",
  checkInput(listDeadLetterSchema),
  catchErrors(adminController.listDeadLetterEvents),
);
adminRoutes.post(
  "/system/dead-letter/:eventId/retry",
  checkInput(deadLetterActionSchema),
  catchErrors(adminController.retryDeadLetterEvent),
);
adminRoutes.post(
  "/system/dead-letter/:eventId/discard",
  checkInput(deadLetterActionSchema),
  catchErrors(adminController.discardDeadLetterEvent),
);
adminRoutes.post(
  "/platform/subscription-plans",
  checkInput(createSubscriptionPlanSchema),
  catchErrors(adminController.createSubscriptionPlan),
);
adminRoutes.get(
  "/platform/subscription-plans",
  checkInput(listSubscriptionPlanSchema),
  catchErrors(adminController.listSubscriptionPlans),
);
adminRoutes.get(
  "/platform/subscription-plans/:planId",
  checkInput(subscriptionPlanParamSchema),
  catchErrors(adminController.getSubscriptionPlan),
);
adminRoutes.patch(
  "/platform/subscription-plans/:planId",
  checkInput(updateSubscriptionPlanSchema),
  catchErrors(adminController.updateSubscriptionPlan),
);
adminRoutes.delete(
  "/platform/subscription-plans/:planId",
  checkInput(subscriptionPlanParamSchema),
  catchErrors(adminController.deleteSubscriptionPlan),
);
adminRoutes.get(
  "/platform/subscriptions",
  checkInput(listPlatformSubscriptionsSchema),
  catchErrors(adminController.listPlatformSubscriptions),
);
adminRoutes.patch(
  "/platform/subscriptions/:subscriptionId/status",
  checkInput(updatePlatformSubscriptionStatusSchema),
  catchErrors(adminController.updatePlatformSubscriptionStatus),
);
adminRoutes.post(
  "/platform/fee-config",
  checkInput(createPlatformFeeConfigSchema),
  catchErrors(adminController.createPlatformFeeConfig),
);
adminRoutes.get(
  "/platform/fee-config",
  checkInput(listPlatformFeeConfigSchema),
  catchErrors(adminController.listPlatformFeeConfigs),
);
adminRoutes.get(
  "/platform/fee-config/:configId",
  checkInput(platformFeeConfigParamSchema),
  catchErrors(adminController.getPlatformFeeConfig),
);
adminRoutes.patch(
  "/platform/fee-config/:configId",
  checkInput(updatePlatformFeeConfigSchema),
  catchErrors(adminController.updatePlatformFeeConfig),
);
adminRoutes.delete(
  "/platform/fee-config/:configId",
  checkInput(platformFeeConfigParamSchema),
  catchErrors(adminController.deletePlatformFeeConfig),
);

// Platform Management Routes
adminRoutes.post(
  "/platform/categories",
  checkInput(createCategorySchema),
  catchErrors(platformController.createCategory),
);
adminRoutes.get(
  "/platform/categories",
  checkInput(listCategoriesSchema),
  catchErrors(platformController.listCategories),
);
adminRoutes.get(
  "/platform/categories/:categoryKey",
  checkInput(categoryKeySchema),
  catchErrors(platformController.getCategory),
);
adminRoutes.patch(
  "/platform/categories/:categoryKey",
  checkInput(updateCategorySchema),
  catchErrors(platformController.updateCategory),
);
adminRoutes.delete(
  "/platform/categories/:categoryKey",
  checkInput(categoryKeySchema),
  catchErrors(platformController.deleteCategory),
);

adminRoutes.post(
  "/platform/product-families",
  checkInput(createProductFamilySchema),
  catchErrors(platformController.createProductFamily),
);
adminRoutes.get(
  "/platform/product-families",
  checkInput(listProductFamiliesSchema),
  catchErrors(platformController.listProductFamilies),
);
adminRoutes.get(
  "/platform/product-families/:familyCode",
  checkInput(productFamilyCodeSchema),
  catchErrors(platformController.getProductFamily),
);
adminRoutes.patch(
  "/platform/product-families/:familyCode",
  checkInput(updateProductFamilySchema),
  catchErrors(platformController.updateProductFamily),
);
adminRoutes.delete(
  "/platform/product-families/:familyCode",
  checkInput(productFamilyCodeSchema),
  catchErrors(platformController.deleteProductFamily),
);

adminRoutes.post(
  "/platform/product-variants",
  checkInput(createProductVariantSchema),
  catchErrors(platformController.createProductVariant),
);
adminRoutes.get(
  "/platform/product-variants",
  checkInput(listProductVariantsSchema),
  catchErrors(platformController.listProductVariants),
);
adminRoutes.get(
  "/platform/product-variants/:variantId",
  checkInput(productVariantIdSchema),
  catchErrors(platformController.getProductVariant),
);
adminRoutes.patch(
  "/platform/product-variants/:variantId",
  checkInput(updateProductVariantSchema),
  catchErrors(platformController.updateProductVariant),
);
adminRoutes.delete(
  "/platform/product-variants/:variantId",
  checkInput(productVariantIdSchema),
  catchErrors(platformController.deleteProductVariant),
);

adminRoutes.post(
  "/platform/hsn-codes",
  checkInput(createHsnCodeSchema),
  catchErrors(platformController.createHsnCode),
);
adminRoutes.get(
  "/platform/hsn-codes",
  checkInput(listHsnCodesSchema),
  catchErrors(platformController.listHsnCodes),
);
adminRoutes.get(
  "/platform/hsn-codes/:hsnCode",
  checkInput(hsnCodeSchema),
  catchErrors(platformController.getHsnCode),
);
adminRoutes.patch(
  "/platform/hsn-codes/:hsnCode",
  checkInput(updateHsnCodeSchema),
  catchErrors(platformController.updateHsnCode),
);
adminRoutes.delete(
  "/platform/hsn-codes/:hsnCode",
  checkInput(hsnCodeSchema),
  catchErrors(platformController.deleteHsnCode),
);

adminRoutes.post(
  "/platform/geography",
  checkInput(createGeographySchema),
  catchErrors(platformController.createGeography),
);
adminRoutes.get(
  "/platform/geography",
  checkInput(listGeographiesSchema),
  catchErrors(platformController.listGeographies),
);
adminRoutes.get(
  "/platform/geography/:countryCode",
  checkInput(geographyCodeSchema),
  catchErrors(platformController.getGeography),
);
adminRoutes.patch(
  "/platform/geography/:countryCode",
  checkInput(updateGeographySchema),
  catchErrors(platformController.updateGeography),
);
adminRoutes.delete(
  "/platform/geography/:countryCode",
  checkInput(geographyCodeSchema),
  catchErrors(platformController.deleteGeography),
);

adminRoutes.post(
  "/platform/content-pages",
  checkInput(createContentPageSchema),
  catchErrors(platformController.createContentPage),
);
adminRoutes.get(
  "/platform/content-pages",
  checkInput(listContentPagesSchema),
  catchErrors(platformController.listContentPages),
);
adminRoutes.get(
  "/platform/content-pages/:slug",
  checkInput(contentPageSlugSchema),
  catchErrors(platformController.getContentPage),
);
adminRoutes.patch(
  "/platform/content-pages/:slug",
  checkInput(updateContentPageSchema),
  catchErrors(platformController.updateContentPage),
);
adminRoutes.delete(
  "/platform/content-pages/:slug",
  checkInput(contentPageSlugSchema),
  catchErrors(platformController.deleteContentPage),
);

module.exports = { adminRoutes };
