const MODULE_CATALOG = [
  {
    tab: "Access Control",
    slug: "rbac",
    name: "RBAC Management",
    description: "Roles, permissions, and access assignments",
    icon: "shield",
    order: 1,
    forPlatform: true,
    forSeller: false,
    apiPath: "/rbac",
  },
  {
    tab: "Admin",
    slug: "admin",
    name: "Admin Dashboard",
    description: "Admin panel and operational controls",
    icon: "dashboard",
    order: 2,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin",
  },
  {
    tab: "Users & Sellers",
    slug: "users",
    name: "User Management",
    description: "Customer accounts, profiles, and KYC",
    icon: "user",
    order: 3,
    forPlatform: true,
    forSeller: false,
    apiPath: "/users",
  },
  {
    tab: "Users & Sellers",
    slug: "sellers",
    name: "Seller Management",
    description: "Seller onboarding, profiles, and sub-admins",
    icon: "store",
    order: 4,
    forPlatform: true,
    forSeller: true,
    apiPath: "/sellers",
  },
  {
    tab: "Users & Sellers",
    slug: "sellers/commissions",
    name: "Seller Commission Management",
    description: "Seller commissions, settlements, and payouts",
    icon: "percent",
    order: 5,
    forPlatform: false,
    forSeller: true,
    apiPath: "/sellers/commissions",
  },
  {
    tab: "Catalog",
    slug: "products",
    name: "Product Management",
    description: "Product catalog, moderation, and seller products",
    icon: "box",
    order: 6,
    forPlatform: true,
    forSeller: true,
    apiPath: "/products",
  },
  {
    tab: "Catalog",
    slug: "platform",
    name: "Platform Catalog",
    description: "Categories, product families, HSN codes, and geography",
    icon: "settings",
    order: 7,
    forPlatform: true,
    forSeller: false,
    apiPath: "/platform",
  },
  {
    tab: "Content",
    slug: "cms",
    name: "CMS Management",
    description:
      "Static pages, legal policies, FAQs, banners, footer links, and help content",
    icon: "file-text",
    order: 8,
    forPlatform: true,
    forSeller: false,
    apiPath: "/platform/cms",
    apiAliases: ["/admin/platform/content-pages", "/pricing/promotion-banners"],
    contentTypes: [
      "legal",
      "faq",
      "banner",
      "promotion_banner",
      "footer",
      "company",
      "help",
      "policy",
      "page",
    ],
    examples: [
      "terms-and-conditions",
      "privacy-policy",
      "return-refund-policy",
      "shipping-policy",
      "faq",
      "home-hero-banner",
      "promotion-banners",
      "about-us",
      "contact-us",
    ],
  },
  {
    tab: "Catalog",
    slug: "warranty",
    name: "Warranty Management",
    description: "Warranty registration and warranty claim handling",
    icon: "badge-check",
    order: 9,
    forPlatform: true,
    forSeller: false,
    apiPath: "/warranty",
  },
  {
    tab: "Shopping",
    slug: "carts",
    name: "Cart Management",
    description: "Shopping carts and checkout baskets",
    icon: "shopping-bag",
    order: 10,
    forPlatform: true,
    forSeller: false,
    apiPath: "/carts",
  },
  {
    tab: "Shopping",
    slug: "orders",
    name: "Order Management",
    description: "Orders, seller orders, cancellations, and status updates",
    icon: "shopping-cart",
    order: 11,
    forPlatform: true,
    forSeller: true,
    apiPath: "/orders",
  },
  {
    tab: "Shopping",
    slug: "returns",
    name: "Return Management",
    description: "Returns, refunds, and reverse logistics",
    icon: "undo",
    order: 12,
    forPlatform: true,
    forSeller: true,
    apiPath: "/returns",
  },
  {
    tab: "Shopping",
    slug: "delivery",
    name: "Delivery Management",
    description: "Delivery serviceability, e-way bills, and tracking",
    icon: "truck",
    order: 13,
    forPlatform: true,
    forSeller: true,
    apiPath: "/delivery",
  },
  {
    tab: "Payments & Finance",
    slug: "payments",
    name: "Payment Management",
    description: "Payments, refunds, and payment operations",
    icon: "credit-card",
    order: 14,
    forPlatform: true,
    forSeller: false,
    apiPath: "/payments",
  },
  {
    tab: "Payments & Finance",
    slug: "wallets",
    name: "Wallet Management",
    description: "Wallet balances and wallet transactions",
    icon: "wallet",
    order: 15,
    forPlatform: true,
    forSeller: false,
    apiPath: "/wallets",
  },
  {
    tab: "Payments & Finance",
    slug: "tax",
    name: "Tax Management",
    description: "Tax invoices, tax reports, and filings",
    icon: "receipt",
    order: 16,
    forPlatform: true,
    forSeller: false,
    apiPath: "/tax",
  },
  {
    tab: "Payments & Finance",
    slug: "subscriptions",
    name: "Subscription Management",
    description: "Plans, subscriptions, and platform fees",
    icon: "repeat",
    order: 17,
    forPlatform: true,
    forSeller: false,
    apiPath: "/subscriptions",
  },
  {
    tab: "Marketing",
    slug: "pricing",
    name: "Pricing & Promotions",
    description: "Coupons, discounts, and pricing controls",
    icon: "tag",
    order: 18,
    forPlatform: true,
    forSeller: true,
    apiPath: "/pricing",
  },
  {
    tab: "Marketing",
    slug: "dynamic-pricing",
    name: "Dynamic Pricing",
    description: "Dynamic pricing rules and price adjustments",
    icon: "activity",
    order: 19,
    forPlatform: true,
    forSeller: false,
    apiPath: "/dynamic-pricing",
  },
  {
    tab: "Marketing",
    slug: "loyalty",
    name: "Loyalty Management",
    description: "Loyalty points and customer rewards",
    icon: "gift",
    order: 20,
    forPlatform: true,
    forSeller: false,
    apiPath: "/loyalty",
  },
  {
    tab: "Marketing",
    slug: "referral",
    name: "Referral Commerce",
    description: "Influencers, referral codes, commission rules, payouts, and reports",
    icon: "share-2",
    order: 21,
    forPlatform: true,
    forSeller: false,
    apiPath: "/admin/referral",
  },
  {
    tab: "Marketing",
    slug: "recommendations",
    name: "Recommendation Management",
    description: "Product recommendations and personalization",
    icon: "sparkles",
    order: 22,
    forPlatform: true,
    forSeller: false,
    apiPath: "/recommendations",
  },
  {
    tab: "Marketing",
    slug: "notifications",
    name: "Notification Management",
    description: "Notifications and communication preferences",
    icon: "bell",
    order: 23,
    forPlatform: true,
    forSeller: true,
    apiPath: "/notifications",
  },
  {
    tab: "Insights & Risk",
    slug: "analytics",
    name: "Analytics",
    description: "Analytics, tracking events, and reporting",
    icon: "chart",
    order: 24,
    forPlatform: true,
    forSeller: true,
    apiPath: "/analytics",
  },
  {
    tab: "Insights & Risk",
    slug: "fraud",
    name: "Fraud Management",
    description: "Fraud detection and risk review",
    icon: "alert-triangle",
    order: 25,
    forPlatform: true,
    forSeller: false,
    apiPath: "/fraud",
  },
];

const DEFAULT_PLATFORM_MODULES = MODULE_CATALOG.filter(
  (module) => module.forPlatform !== false,
).map((module) => module.slug);

const DEFAULT_SELLER_MODULES = MODULE_CATALOG.filter(
  (module) => module.forSeller === true,
).map((module) => module.slug);

const API_MODULES = [
  "auth",
  ...MODULE_CATALOG.map((module) => module.slug),
  "meta",
];

const MODULE_CATALOG_BY_SLUG = new Map(
  MODULE_CATALOG.map((module) => [module.slug, module]),
);

function getModuleCatalogItem(slug) {
  return MODULE_CATALOG_BY_SLUG.get(slug) || null;
}

function groupModuleCatalogByTab(modules = MODULE_CATALOG) {
  return modules.reduce((tabs, module) => {
    let targetTab = tabs.find((tab) => tab.tab === module.tab);
    if (!targetTab) {
      targetTab = {
        tab: module.tab,
        modules: [],
      };
      tabs.push(targetTab);
    }

    targetTab.modules.push(module);
    return tabs;
  }, []);
}

module.exports = {
  MODULE_CATALOG,
  DEFAULT_PLATFORM_MODULES,
  DEFAULT_SELLER_MODULES,
  API_MODULES,
  getModuleCatalogItem,
  groupModuleCatalogByTab,
};
